version: '3.8'

services:
  postgres:
    image: postgres
    container_name: store
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54250:5432"