debug: false
server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://dpg-cjb5b7ocfp5c73b9f350-a:5432/store_4g4n
    username: heppyadmin
    password: mjWEzk2Wq0lLBb6CWek4utZj7bYpFB9V
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        connection:
          pool_size: 10
          autocommit: true




gcp:
  vars:
    admin.user: ${ADMIN_USERNAME:test@gmail.com}
    admin.password: ${ADMIN_PASSWORD:12345}
