debug: false
server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: postgres://st_19qm_user:edgE7VGlhZCk2knu9L1SQkPM3JTJtypQ@dpg-cjeksgs1ja0c738av4d0-a/st_19qm
    username: st_19qm_user
    password: edgE7VGlhZCk2knu9L1SQkPM3JTJtypQ
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        connection:
          pool_size: 10
          autocommit: true
